In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6])

In [3]:
print(a)

[1 2 3 4 5 6]


In [4]:
print(a,a.ndim,sep="\n")

[1 2 3 4 5 6]
1


In [5]:
b=np.array([[1,2],[3,4]])
print(b,b.ndim,sep="\n")

[[1 2]
 [3 4]]
2


In [6]:
c=np.arange(1,21)
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [7]:
d=np.arange(10,30,2)
print(d,end="\n---------------------------------------------------\n")
d.shape=(2,5)
print(d)

[10 12 14 16 18 20 22 24 26 28]
---------------------------------------------------
[[10 12 14 16 18]
 [20 22 24 26 28]]


In [8]:
x=np.empty([3,2],dtype=int)
x=np.zeros(10)

In [9]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
x=np.ones(10)

In [11]:
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
x=np.array([np.arange(1,4),np.arange(4,7)])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
x.ndim

2

In [14]:
x[0]

array([1, 2, 3])

In [15]:
x[:,0]

array([1, 4])

In [16]:
x[1,1]

5

In [17]:
c.shape=(5,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [18]:
c[1:,0:3]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [19]:
#copy one array to another
y=c[1:,0:3].copy()
y

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [20]:
y.transpose()

array([[ 5,  9, 13, 17],
       [ 6, 10, 14, 18],
       [ 7, 11, 15, 19]])

In [21]:
y.T

array([[ 5,  9, 13, 17],
       [ 6, 10, 14, 18],
       [ 7, 11, 15, 19]])

In [22]:
y

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [23]:
y+y

array([[10, 12, 14],
       [18, 20, 22],
       [26, 28, 30],
       [34, 36, 38]])

In [24]:
y*y

array([[ 25,  36,  49],
       [ 81, 100, 121],
       [169, 196, 225],
       [289, 324, 361]])

In [25]:
np.add(y,y)

array([[10, 12, 14],
       [18, 20, 22],
       [26, 28, 30],
       [34, 36, 38]])

In [26]:
np.subtract(y,y)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
np.multiply(y,y)

array([[ 25,  36,  49],
       [ 81, 100, 121],
       [169, 196, 225],
       [289, 324, 361]])

In [28]:
np.sqrt(y)

array([[2.23606798, 2.44948974, 2.64575131],
       [3.        , 3.16227766, 3.31662479],
       [3.60555128, 3.74165739, 3.87298335],
       [4.12310563, 4.24264069, 4.35889894]])